import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const disciplines = [
  ["AI Engineering", "Pengembangan sistem dan aplikasi yang memanfaatkan Artificial Intelligence untuk otomatisasi, pemrosesan informasi, interaksi pengguna, dan intelligent system.", "AI Assistant · AI Integration · Local AI / LLM · AI Automation"],
  ["Software Development", "Pengembangan software dan aplikasi untuk mengubah ide menjadi produk digital yang menyelesaikan kebutuhan tertentu.", "Custom Software · Internal Tools · Desktop Application · Digital Platform"],
  ["Android Development", "Pengembangan aplikasi Android untuk kebutuhan bisnis, pendidikan, hiburan, utilitas, dan project kustom.", "Business · Educational · Entertainment · Utility Application"],
  ["Web Development", "Pengembangan website dan web application modern untuk company profile, dashboard, internal system, dan platform digital.", "Company Profile · Dashboard · Web Application · Internal System"],
  ["Automation", "Pengembangan sistem otomatisasi untuk membantu pekerjaan digital menjadi lebih efisien dan terarah.", "Workflow · Processing · Developer Tools"],
  ["Research & Development", "Eksplorasi teknologi baru melalui prototype dan experimental project untuk menemukan pendekatan yang tepat.", "Prototype · Experiment · Product Exploration"],
  ["AI Education", "Program edukasi teknologi sebagai salah satu aktivitas Extreme Studios, bukan identitas utama studio.", "AI Workshop · AI Engineer Basic · Technology Training"]
];

const capabilities = ["Artificial Intelligence", "Software Engineering", "Android Development", "Web Development", "Automation", "Local AI / LLM", "Prototype Development", "Research & Development"];

const process = [["IDE", "Setiap project dimulai dari sebuah ide atau permasalahan yang ingin diselesaikan."], ["EXPERIMENT", "Kami melakukan eksplorasi teknologi dan membuat prototype."], ["ENGINEERING", "Ide dikembangkan menjadi sistem atau aplikasi yang dapat digunakan."], ["TESTING", "Software diuji dan diperbaiki untuk meningkatkan stabilitas dan pengalaman pengguna."], ["PRODUCT", "Project dikembangkan menjadi produk digital yang dapat digunakan dan terus dikembangkan."]];

const projects = [
  ["DIANA Smart Assistant AI", "AI Engineering · Desktop Application", "Asisten AI personal berbasis Electron untuk keluarga, dengan integrasi Pixi.js dan Live2D.", "diana"],
  ["Extreme Studios Guitar FX", "Android · Audio Technology", "Aplikasi Guitar FX Android yang dibangun dengan Kotlin, Jetpack Compose, serta komponen C++17.", "/featured/guitar-fx.png"],
  ["Movie HUB", "Android · Entertainment", "Aplikasi Android untuk pengalaman informasi dan koleksi tontonan, menggunakan Kotlin, Room, dan Coroutines.", "/featured/movie-hub.png"],
  ["Extreme Studios HUB", "Software Distribution", "Pusat distribusi aplikasi untuk mengelola katalog APK dan software PC dalam satu tempat.", "/mockups/extreme-studios-hub.png"],
  ["Auto Cut Video", "Desktop Automation", "Software desktop untuk membantu pemotongan video highlight dan ekspor XML untuk workflow editing.", "/mockups/auto-cut-video.png"],
  ["Portal Arek Musik", "Web Platform", "Platform streaming musik untuk band indie mempublikasikan karya dan membangun identitas digital.", "/mockups/portal-arek-musik.png"]
];

function CoreVisual({ compact = false }) { return <div className={`profile-core ${compact ? "profile-core--compact" : ""}`} aria-hidden="true"><div className="profile-core__grid" /><div className="profile-core__ring" /><div className="profile-core__cube">ES</div><div className="profile-core__chip">AI<br /><span>ENGINEERING</span></div></div>; }
function DianaVisual() { return <div className="profile-diana" aria-hidden="true"><div className="profile-diana__orb">D</div><span>CONTEXT</span><i /><i /><i /></div>; }

export const metadata = { title: "Profile | Extreme Studios", description: "Company profile Extreme Studios: AI Engineering & Software Development." };

export default function ProfilePage() {
  return <><Navbar /><main className="profile-page">
    <section className="profile-hero"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 pb-20 pt-36 md:grid-cols-[1fr_.9fr] md:px-8"><div><p className="eyebrow">Extreme Studios</p><h1>Kami Membangun Teknologi<br /><span>dari Ide Menjadi Produk.</span></h1><p className="profile-lead">Extreme Studios adalah studio teknologi yang berfokus pada pengembangan Artificial Intelligence, software, aplikasi Android, web application, automation, dan eksplorasi teknologi digital.</p><p className="profile-copy">Kami mengembangkan ide melalui proses eksperimen, engineering, pengujian, dan pengembangan hingga menjadi solusi yang dapat digunakan di dunia nyata.</p></div><CoreVisual /></div></section>

    <section className="profile-section"><div className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-24 md:grid-cols-[.85fr_1.15fr] md:px-8"><div><p className="eyebrow">Tentang Extreme Studios</p><h2>Studio teknologi untuk <span>eksplorasi dan solusi nyata.</span></h2><p className="profile-copy">Extreme Studios merupakan studio teknologi yang berfokus pada AI Engineering dan Software Development. Kami mengeksplorasi bagaimana Artificial Intelligence dan teknologi software dapat digunakan untuk membangun aplikasi, sistem, tools, dan produk digital.</p><p className="profile-copy">Kami tidak hanya mengembangkan software sebagai produk akhir, tetapi juga melakukan eksperimen, pengujian teknologi, pengembangan prototype, dan Research &amp; Development untuk menemukan solusi baru.</p></div><div className="profile-screen"><div className="profile-screen__top"><i /><i /><i /></div><p>system.architecture</p><strong>AI / SOFTWARE / ANDROID</strong><div className="profile-screen__lines"><i /><i /><i /><i /></div><span>PRODUCT<br />LAB</span></div></div></section>

    <section className="profile-section profile-section--shade"><div className="mx-auto max-w-6xl px-5 py-24 md:px-8"><p className="eyebrow">Apa yang Kami Kerjakan</p><h2 className="max-w-2xl">Membangun teknologi yang <span>berguna dan berkembang.</span></h2><div className="discipline-list">{disciplines.map(([title, description, examples], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{description}</p><small>{examples}</small></div></article>)}</div></div></section>

    <section className="profile-section"><div className="mx-auto max-w-6xl px-5 py-24 md:px-8"><div className="grid gap-10 md:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow">Kemampuan Kami</p><h2>Teknologi yang kami gunakan untuk <span>mewujudkan produk.</span></h2></div><div className="capability-grid">{capabilities.map((item, index) => <div key={item}><b>0{index + 1}</b><span>{item}</span></div>)}</div></div></div></section>

    <section className="profile-section profile-process"><div className="mx-auto max-w-6xl px-5 py-24 md:px-8"><p className="eyebrow">Bagaimana Kami Membangun Teknologi</p><h2>Proses yang membawa ide menjadi <span>produk digital.</span></h2><div className="process-line">{process.map(([title, description], index) => <article key={title}><b>0{index + 1}</b><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>

    <section className="profile-section profile-section--shade"><div className="mx-auto max-w-6xl px-5 py-24 md:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Project Extreme Studios</p><h2>Project nyata dari <span>berbagai bidang teknologi.</span></h2></div><a href="/projects" className="text-sm font-bold uppercase tracking-wide text-cyan">Lihat Portfolio Lengkap →</a></div><article className="diana-feature mt-10"><div className="diana-feature__visual"><DianaVisual /></div><div><p className="eyebrow">Featured AI Project</p><h3>DIANA Smart Assistant AI</h3><p>DIANA adalah project aplikasi desktop asisten AI personal untuk keluarga. Project ini menggunakan Electron dengan JavaScript serta memanfaatkan Pixi.js dan Live2D untuk tampilan avatar interaktif.</p><div className="project-facts"><span>Desktop Application</span><span>Electron</span><span>JavaScript</span><span>Pixi.js / Live2D</span></div><p className="text-slate-400">Tujuan project: menyediakan companion digital personal melalui antarmuka desktop yang interaktif.</p></div></article><div className="profile-project-grid">{projects.slice(1).map(([title, category, description, image]) => <article key={title} className="project-card"><div className="project-visual"><img src={image} alt={`${title} mockup`} /></div><div className="p-6"><p className="eyebrow">{category}</p><h3>{title}</h3><p>{description}</p></div></article>)}</div></div></section>

    <section className="profile-section"><div className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-24 md:grid-cols-[1.12fr_.88fr] md:px-8"><div><p className="eyebrow">Teknologi yang Kami Gunakan</p><h2>Stack yang <span>terverifikasi di project.</span></h2><p className="profile-copy">Project yang diaudit menggunakan Next.js, React, Tailwind CSS, JavaScript, Electron, Pixi.js, Live2D, Kotlin, Jetpack Compose, C++17, Android Room, dan Kotlin Coroutines. Teknologi dipilih mengikuti kebutuhan setiap produk.</p><div className="stack-list">{["Next.js", "React", "Tailwind CSS", "JavaScript", "Electron", "Pixi.js", "Live2D", "Kotlin", "Jetpack Compose", "C++17", "Android Room", "Coroutines"].map((item) => <span key={item}>{item}</span>)}</div></div><CoreVisual compact /></div></section>

    <section className="profile-section profile-section--shade"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-24 md:grid-cols-2 md:px-8"><div><p className="eyebrow">Research &amp; Development</p><h2>Ruang untuk <span>bereksperimen.</span></h2><p className="profile-copy">Extreme Studios melakukan eksplorasi dan pengembangan teknologi melalui project internal dan prototype. Pendekatan ini membantu kami menguji arah teknologi sebelum dikembangkan menjadi produk yang lebih matang.</p></div><div className="rd-panel"><b>R&amp;D</b><span>PROTOTYPE</span><i /><i /><i /></div></div></section>

    <section className="profile-section"><div className="mx-auto max-w-6xl px-5 py-24 md:px-8"><p className="eyebrow">Programs &amp; Events</p><article className="profile-program"><div><span className="tag">Program Aktif</span><h2>Pelatihan AI Engineer Basic</h2><p>Program pengenalan Artificial Intelligence dan pembuatan aplikasi Android dengan bantuan AI dan Android Studio untuk siswa SD kelas 4–6.</p><div className="profile-program__facts"><span>4x Pertemuan<br /><b>1 Jam / Pertemuan</b></span><span>Biaya<br /><b>Rp250.000 / Siswa</b></span><span>Kuota<br /><b>5–10 Siswa</b></span></div></div><a href="/programs/ai-engineer-basic" className="button-secondary">Lihat Informasi Pelatihan <b>→</b></a></article></div></section>

    <section className="profile-cta"><div className="mx-auto max-w-6xl px-5 py-20 text-center md:px-8"><p className="eyebrow">Kolaborasi</p><h2>Punya Ide yang Ingin <span>Dikembangkan?</span></h2><p>Extreme Studios terbuka untuk eksplorasi ide, pengembangan software, aplikasi, dan kolaborasi teknologi.</p><a href="/#contact" className="button-primary">Hubungi Extreme Studios <b>→</b></a></div></section>
  </main><Footer /></>;
}
