"use client";

import { useState } from "react";
import DianaChat from "@/components/DianaChat";

const looks = [
  ["Paes Ageng", "Rias pengantin Jawa yang anggun", "/demo-mua/makeup-session.png"],
  ["Kebaya Akad", "Elegan, hangat, dan timeless", "/demo-mua/bridal-fashion.png"],
  ["Hijab Modern", "Clean, graceful, tetap personal", "/demo-mua/bridal-fashion.png"],
  ["Pelaminan Joglo", "Dekorasi lokal yang berkarakter", "/demo-mua/wedding-decor.png"]
];
const gallery = [
  ["Rias Paes Jawa", "Proses makeup pengantin yang tenang, rapi, dan personal.", "/demo-mua/makeup-session.png", "Proses merias"],
  ["Koleksi Kebaya & Gaun", "Pilihan kebaya, gaun, dan look bridal yang lebih beragam.", "/demo-mua/bridal-fashion.png", "Baju pernikahan"],
  ["Pelaminan Jawa", "Inspirasi gebyok, janur, bunga, dan dekorasi lokal.", "/demo-mua/wedding-decor.png", "Pilihan dekorasi"]
];
const packages = [
  ["The Intimate", "Rp1.250.000", "Untuk akad yang intimate", ["Makeup akad", "Hijab styling", "Touch-up 1x"]],
  ["The Signature", "Rp2.250.000", "Look lengkap untuk hari spesial", ["Makeup pengantin", "Hairdo atau hijab styling", "Touch-up sampai acara selesai"]],
  ["The Celebration", "Rp3.500.000", "Untuk pengantin dan keluarga", ["Makeup pengantin", "2 makeup keluarga", "Hairdo, hijab styling, dan touch-up"]]
];

export default function MuaDemoSite() {
  const [booked, setBooked] = useState(false);
  const [selected, setSelected] = useState(packages[1][0]);
  return <main className="demo-mua"><DianaChat vertical="mua" displayName="Chat Assistant" />
    <div className="demo-mua__demo-bar"><span>WEBSITE DEMO</span><a href="/mua">Ingin website seperti ini? Lihat paket Extreme Studios →</a></div>
    <header className="demo-mua__nav"><a href="#demo-home" className="demo-mua__logo"><i>L</i><span>LUMINA<small>MAKEUP ARTIST</small></span></a><nav><a href="#demo-about">Tentang</a><a href="#demo-portfolio">Portfolio</a><a href="#demo-packages">Paket</a><a href="#demo-booking">Booking</a></nav><a href="#demo-booking" className="demo-mua__nav-cta">Cek ketersediaan</a></header>
    <section id="demo-home" className="demo-mua__hero"><div className="demo-mua__hero-copy"><p className="demo-mua__eyebrow">MAKEUP FOR YOUR MOMENT</p><h1>Make your beauty<br /><em>more meaningful.</em></h1><p>Riasan yang terasa seperti diri kamu sendiri—lebih percaya diri, lebih bersinar, dan siap menyimpan momen selamanya.</p><div><a href="#demo-packages" className="demo-mua__button">Lihat paket <b>→</b></a><a href="#demo-portfolio" className="demo-mua__text-link">Lihat portfolio</a></div></div><div className="demo-mua__hero-art"><div className="demo-mua__portrait"><span>BRIDAL<br /><i>beauty</i></span></div><div className="demo-mua__hero-note"><small>AVAILABLE FOR</small><b>2026 BRIDES</b><span>Surabaya · Sidoarjo · Jawa Timur</span></div><div className="demo-mua__hero-stamp">L<br /><small>LM</small></div></div></section>
    <section id="demo-about" className="demo-mua__intro"><p className="demo-mua__eyebrow">A LITTLE ABOUT US</p><h2>Riasan yang memperkuat<br /><em>cerita kamu.</em></h2><p>Setiap wajah punya karakter dan setiap acara punya cerita. Lumina membantu kamu menemukan look yang nyaman, elegan, dan cocok untuk momen yang paling berarti.</p><div className="demo-mua__metrics"><span><b>8+</b><small>Tahun pengalaman</small></span><span><b>500+</b><small>Brides served</small></span><span><b>4.9</b><small>Client rating</small></span></div></section>
    <section className="demo-mua__gallery-suite"><div className="demo-mua__section-head"><div><p className="demo-mua__eyebrow">YOUR WEDDING, YOUR WAY</p><h2>Inspirasi untuk<br /><em>momen kamu.</em></h2></div><p>Mulai dari proses makeup sampai dekorasi, semua bisa disesuaikan dengan cerita dan karakter acara kamu.</p></div><div className="demo-mua__gallery-grid">{gallery.map(([title, note, image, label]) => <article className="demo-mua__gallery-card" key={title}><div className="demo-mua__gallery-image"><img src={image} alt={title} loading="lazy" /></div><div className="demo-mua__gallery-copy"><span>{label}</span><h3>{title}</h3><p>{note}</p></div></article>)}</div></section>
    <section id="demo-portfolio" className="demo-mua__portfolio"><div className="demo-mua__section-head"><div><p className="demo-mua__eyebrow">THE PORTFOLIO</p><h2>Looks we love.</h2></div><a href="#demo-booking">Konsultasikan look kamu →</a></div><div className="demo-mua__look-grid">{looks.map(([name, note, image], index) => <article className={`demo-mua__look demo-mua__look--${index + 1}`} key={name}><div><img src={image} alt={name} loading="lazy" /><span>{String(index + 1).padStart(2, "0")}</span></div><h3>{name}</h3><p>{note}</p></article>)}</div></section>
    <section className="demo-mua__assistant-preview"><div><p className="demo-mua__eyebrow">CHAT ASSISTANT</p><h2>Calon client tidak perlu menunggu.</h2><p>Chat assistant membantu menjawab pertanyaan dasar, menjelaskan paket, dan mengarahkan calon pengantin ke booking.</p><button type="button" className="demo-mua__button" onClick={() => window.dispatchEvent(new CustomEvent("open-diana", { detail: { vertical: "mua" } }))}>Coba chat assistant <b>→</b></button></div><div className="demo-mua__assistant-window"><div className="demo-mua__assistant-head"><span>✦</span><div><b>Chat Assistant</b><small>Online · siap membantu</small></div><i>•••</i></div><div className="demo-mua__assistant-messages"><p className="user">Kak, paket wedding berapa ya?</p><p>Halo Kak! Ada paket mulai Rp1.250.000. Mau saya bantu pilihkan sesuai acara kamu?</p><p className="user">Tanggal 12 Oktober masih tersedia?</p><p>Saya bisa bantu cek jadwal dan lanjutkan ke booking demo.</p></div><div className="demo-mua__assistant-input">Ketik pesanmu di sini... <span>↗</span></div></div></section>
    <section id="demo-packages" className="demo-mua__packages"><div className="demo-mua__section-head"><div><p className="demo-mua__eyebrow">PAKET WEDDING</p><h2>Pilih paket yang pas.</h2></div><p>Contoh isi paket di bawah ini bisa disesuaikan dengan layanan dan harga MUA kamu.</p></div><div className="demo-mua__package-grid">{packages.map(([name, price, note, includes], index) => <button className={`demo-mua__package ${selected === name ? "selected" : ""}`} key={name} onClick={() => setSelected(name)}><small>0{index + 1}</small><h3>{name}</h3><p>{note}</p><strong>{price}</strong><ul>{includes.map((item) => <li key={item}><span>✓</span>{item}</li>)}</ul><span>{selected === name ? "Paket dipilih ✓" : "Pilih paket →"}</span></button>)}</div></section>
    <section id="demo-booking" className="demo-mua__booking"><div><p className="demo-mua__eyebrow">LET'S MAKE IT YOURS</p><h2>Cerita acara kamu<br /><em>dimulai di sini.</em></h2><p>Pilih tanggal dan isi detail singkat. Chat assistant kami juga siap membantu menjawab pertanyaan kamu.</p><div className="demo-mua__booking-facts"><span>✓ Free consultation</span><span>✓ Response within 24 hours</span><span>✓ Demo — no real booking sent</span></div></div>{!booked ? <form onSubmit={(event) => { event.preventDefault(); setBooked(true); }}><label>Nama kamu<input required placeholder="Nama calon pengantin" /></label><label>Nomor WhatsApp<input required type="tel" placeholder="08xxxxxxxxxx" /></label><label>Tanggal acara<input required type="date" /></label><label>Paket pilihan<select value={selected} onChange={(event) => setSelected(event.target.value)}>{packages.map(([name]) => <option key={name}>{name}</option>)}</select></label><button className="demo-mua__button" type="submit">Cek ketersediaan <b>→</b></button></form> : <div className="demo-mua__success"><span>✓</span><h3>Terima kasih, Kak.</h3><p>Ini hanya demo website. Data tidak dikirim ke MUA sungguhan.</p><button onClick={() => setBooked(false)}>Coba lagi</button></div>}</section>
    <footer className="demo-mua__footer"><a href="/mua">Website MUA + Chat Assistant oleh Extreme Studios</a><span>© 2026 Lumina Makeup Artist · Demo</span></footer>
  </main>;
}
