const projects = [{ title: "DIANA Smart Assistant", tag: "AI", type: "AI Engineering · Productivity", desc: "Asisten berbasis AI yang memahami konteks, membantu pekerjaan, dan menjadi companion digital.", visual: "diana" }, { title: "Extreme Studios Guitar FX", tag: "Android", type: "Audio Technology · Android", desc: "Aplikasi multiefek gitar profesional untuk Android dengan kualitas audio tinggi dan performa optimal.", image: "/featured/guitar-fx.png" }, { title: "Movie HUB", tag: "Android", type: "Entertainment · Android", desc: "Aplikasi informasi film dengan review, trailer, rekomendasi personal, dan daftar tontonan.", image: "/featured/movie-hub.png" }];

const parfiScreens = [
  ["/project-parfi-jatim/parfi-home.png", "Beranda website PARFI Jatim"],
  ["/project-parfi-jatim/parfi-news.png", "Portal berita PARFI Jatim"],
  ["/project-parfi-jatim/parfi-agenda.png", "Agenda kegiatan organisasi"],
  ["/project-parfi-jatim/parfi-film-gallery.png", "Galeri film PARFI Jatim"]
];

function DianaVisual() { return <div className="diana-visual"><img src="/generated-diana-ai.png" alt="Visual DIANA Smart Assistant AI" /></div>; }

export default function OtherProjects() { return <section id="projects" className="mx-auto max-w-6xl px-5 py-20 md:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Project Unggulan</p><h2 className="mt-3 text-3xl font-medium text-white md:text-4xl">Teknologi Nyata. Solusi Berdampak.</h2></div><a href="/projects" className="text-sm font-bold uppercase tracking-wide text-cyan">Lihat Semua Project&nbsp; →</a></div><div className="mt-8 grid gap-5 md:grid-cols-3"><article className="project-card project-card--web-feature md:col-span-3"><div className="project-web-feature__gallery">{parfiScreens.map(([image, alt]) => <img key={image} src={image} alt={alt} loading="lazy" />)}</div><div className="project-web-feature__copy"><p className="eyebrow">Web Project · Organization Portal</p><h3>Website Resmi PARFI Jawa Timur <span className="tag">Website</span></h3><p>Portal website untuk profil organisasi, berita, agenda kegiatan, dan galeri film. Ini adalah hasil pembuatan website responsif—bukan aplikasi Android atau desktop.</p><div className="project-web-feature__facts"><span>Website organisasi</span><span>Portal berita</span><span>Agenda</span><span>Galeri film</span></div><div className="project-web-feature__actions"><a href="/projects/web-parfi-jatim">Lihat detail project →</a><a href="https://parfijatim.com" target="_blank" rel="noreferrer">Kunjungi website ↗</a></div></div></article>{projects.map((project) => <article key={project.title} className="project-card"><div className="project-visual">{project.image ? <img src={project.image} alt={`${project.title} mockup`} /> : <DianaVisual />}</div><div className="p-5"><h3 className="text-lg font-medium text-white">{project.title} <span className="tag">{project.tag}</span></h3><p className="mt-3 text-sm leading-6 text-slate-400">{project.desc}</p><p className="mt-5 text-xs font-bold uppercase tracking-wide text-cyan">{project.type}</p></div></article>)}</div></section>; }
